💚 Update setup-ruby to maintained release
Recent runs of our CI pipeline has been failing with the following
error:

```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.5.8 not found
```

This commit migrates our CI pipeline from `actions/setup-ruby` to
`ruby/setup-ruby`, as recommended in the deprecation error.