🐛 Define current_subject in each controller
We've recently started to see the below runtime error in Sentry:

```
ActionView::Template::Error: undefined method `lead?' for #<User:0x00007f69ed22f278>
```

The `lead?` method is defined on our `admin` and `assessor` models,
though it seems that we're now calling it on an instance of `user`. I
suspect this change in behaviour relates to my recent attempts to DRY up
the code, unifying all instances of `current_subject` into a single
method in `application_controller`.

This commit reverts my previous refactoring, allowing each controller
to implement the `current_subject` helper method as appropriate.