🐛 Fix undefined variable `account_owner`
A recent production deploy (linked below) refactors some of the
back-end views, including the addition of a new partial,
`show_company_details`. This partial assumes the presence of a helper
method / instance variable, `account_owner`, most likely because we make
this available in similar views under `CollaboratorsController.rb`.

Unfortunately, the `account_owner` helper isn't defined under
`AccountsController` and users are therefore experiencing a runtime
error:

```
undefined local variable or method `account_owner'
```

This commit resolves the issue by explicitly setting an `@account_owner`
instance variable and referencing this from within the view.

* https://gitlab.bitzesty.com/clients/qae/qae/-/merge_requests/1825/